---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Install some basic packages because LXC containers are bare
      raw: |
        dhclient || true
        if [ -x "$(command -v apt-get)" ]; then
          apt-get update && apt-get install --assume-yes ca-certificates curl python3 python3-apt sudo
        elif [ -x "$(command -v yum)" ]; then
          yum install -y ca-certificates curl python3 sudo
        elif [ -x "$(command -v zypper)" ]; then
          zypper --non-interactive --gpg-auto-import-keys refresh
          zypper --non-interactive install -y ca-certificates ca-certificates-cacert ca-certificates-mozilla curl python3 sudo
        elif [ -x "$(command -v apk)" ]; then
          apk update && apk add ca-certificates curl python3 sudo
        elif [ -x "$(command -v pacman)" ]; then
          pacman -Syu --noconfirm ca-certificates curl python3 sudo
        elif [ -x "$(command -v dnf)" ]; then
          dnf --assumeyes install ca-certificates curl python3 python3-dnf sudo
        fi
