---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"

  tasks:
    - name: Destroy molecule instance(s)
      community.general.lxd_container:
        name: "{{ item.name }}"
        state: absent
        force_stop: "{{ item.force_stop | default(true) }}"
        url: "{{ item.url | default(omit) }}"
        cert_file: "{{ item.cert_file | default(omit) }}"
        key_file: "{{ item.key_file | default(omit) }}"
        trust_password: "{{ item.trust_password | default(omit) }}"
        ignore_volatile_options: "{{ item.ignore_volatile_options | default(false) }}"
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        label: "{{ item.name }}"
      no_log: false
      register: _destroy
      until: not _destroy.failed
      retries: 3
      delay: 10
