---
name: Publish to PyPI

on:
  workflow_run:
    workflows: [ 'tox' ]
    branches: [ 'master' ]
    types: [ 'completed' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    # Runs on base repository only and after tox tests are completed and success
    if: github.repository == 'ansible-community/molecule-lxd' && github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python v3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install tox
        run: python -m pip install tox

      - name: Build dists
        run: tox -e packaging

      # Runs on push to the default branch
      - name: Publish to test.pypi.org
        if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.testpypi_password }}
          repository_url: https://test.pypi.org/legacy/

      # Runs on release publishing
      - name: Publish to pypi.org
        if: github.event_name == 'release'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.pypi_password }}
